layer {
  name: "data_A"
  type: "Input"
  top: "data_A"
  input_param {
    shape: {
    dim: 1
    dim: 1
    dim: 64
    dim: 64
    }
  }
}

layer {
  name: "data_P"
  type: "Input"
  top: "data_P"
  input_param {
    shape: {
    dim: 1
    dim: 1
    dim: 256
    dim: 256
    }
  }
}

# ******************end of data layer******************
# ******************head of tower A********************
layer {
  bottom: "data_A"
  top: "conv0"
  name: "conv0"
  type: "Convolution"
  param {
	name: "conv0_w"
	lr_mult : 1
  }
  param {
    name: "conv0_b"
	lr_mult : 2
  }
  convolution_param {
    num_output: 24
    pad: 3
    kernel_size: 7
    stride: 1
	weight_filler {
		type : "msra"
	}
	bias_filler {
		type : "constant"
	}
  }
}
layer {
  bottom: "conv0"
  top: "conv0"
  name: "conv0_relu"
  type: "ReLU"
}
layer {
  bottom: "conv0"
  top: "pool0"
  name: "pool0"
  type: "Pooling"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
    pad: 0
  }
}
layer {
  bottom: "pool0"
  top: "conv1"
  name: "conv1"
  type: "Convolution"
  param {
	name: "conv1_w"
	lr_mult : 1
  }
  param {
    name: "conv1_b"
	lr_mult : 2
  }
  convolution_param {
    num_output: 64
    pad: 2
    kernel_size: 5
    stride: 1
	weight_filler {
		type : "msra"
	}
	bias_filler {
		type : "constant"
	}
  }
}
layer {
  bottom: "conv1"
  top: "conv1"
  name: "conv1_relu"
  type: "ReLU"
}
layer {
  bottom: "conv1"
  top: "pool1"
  name: "pool1"
  type: "Pooling"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
    pad: 0
  }
}
layer {
  bottom: "pool1"
  top: "conv2"
  name: "conv2"
  type: "Convolution"
  param {
	name: "conv2_w"
	lr_mult : 1
  }
  param {
    name: "conv2_b"
	lr_mult : 2
  }
  convolution_param {
    num_output: 96
    pad: 1
    kernel_size: 3
    stride: 1
	weight_filler {
		type : "msra"
	}
	bias_filler {
		type : "constant"
	}
  }
}
layer {
  bottom: "conv2"
  top: "conv2"
  name: "conv2_relu"
  type: "ReLU"
}
layer {
  bottom: "conv2"
  top: "conv3"
  name: "conv3"
  type: "Convolution"
  param {
	name: "conv3_w"
	lr_mult : 1
  }
  param {
    name: "conv3_b"
	lr_mult : 2
  }
  convolution_param {
    num_output: 96
    pad: 1
    kernel_size: 3
    stride: 1
	weight_filler {
		type : "msra"
	}
	bias_filler {
		type : "constant"
	}
  }
}
layer {
  bottom: "conv3"
  top: "conv3"
  name: "conv3_relu"
  type: "ReLU"
}
layer {
  bottom: "conv3"
  top: "conv4"
  name: "conv4"
  type: "Convolution"
  param {
	name: "conv4_w"
	lr_mult : 1
  }
  param {
    name: "conv4_b"
	lr_mult : 2
  }
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
    stride: 1
	weight_filler {
		type : "msra"
	}
	bias_filler {
		type : "constant"
	}
  }
}
layer {
  bottom: "conv4"
  top: "conv4"
  name: "conv4_relu"
  type: "ReLU"
}
layer {
  bottom: "conv4"
  top: "pool4"
  name: "pool4"
  type: "Pooling"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
    pad: 0
  }
}

layer {
  bottom: "pool4"
  top: "pool4"
  type: "Dropout"
  dropout_param {
    dropout_ratio: 0.5
  }
}

# ******************end of tower A*********************
# ******************head of tower P********************
layer {
  bottom: "data_P"
  top: "conv0_p"
  name: "conv0_p"
  type: "Convolution"
  param {
	name: "conv0_w"
	lr_mult : 1
  }
  param {
    name: "conv0_b"
	lr_mult : 2
  }
  convolution_param {
    num_output: 24
    pad: 3
    kernel_size: 7
    stride: 1
	weight_filler {
		type : "msra"
	}
	bias_filler {
		type : "constant"
	}
  }
}
layer {
  bottom: "conv0_p"
  top: "conv0_p"
  name: "conv0_relu_p"
  type: "ReLU"
}
layer {
  bottom: "conv0_p"
  top: "pool0_p"
  name: "pool0_p"
  type: "Pooling"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
    pad: 0
  }
}
layer {
  bottom: "pool0_p"
  top: "conv1_p"
  name: "conv1_p"
  type: "Convolution"
  param {
	name: "conv1_w"
	lr_mult : 1
  }
  param {
    name: "conv1_b"
	lr_mult : 2
  }
  convolution_param {
    num_output: 64
    pad: 2
    kernel_size: 5
    stride: 1
	weight_filler {
		type : "msra"
	}
	bias_filler {
		type : "constant"
	}
  }
}
layer {
  bottom: "conv1_p"
  top: "conv1_p"
  name: "conv1_relu_p"
  type: "ReLU"
}
layer {
  bottom: "conv1_p"
  top: "pool1_p"
  name: "pool1_p"
  type: "Pooling"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
    pad: 0
  }
}
layer {
  bottom: "pool1_p"
  top: "conv2_p"
  name: "conv2_p"
  type: "Convolution"
  param {
	name: "conv2_w"
	lr_mult : 1
  }
  param {
    name: "conv2_b"
	lr_mult : 2
  }
  convolution_param {
    num_output: 96
    pad: 1
    kernel_size: 3
    stride: 1
	weight_filler {
		type : "msra"
	}
	bias_filler {
		type : "constant"
	}
  }
}
layer {
  bottom: "conv2_p"
  top: "conv2_p"
  name: "conv2_relu_p"
  type: "ReLU"
}
layer {
  bottom: "conv2_p"
  top: "conv3_p"
  name: "conv3_p"
  type: "Convolution"
  param {
	name: "conv3_w"
	lr_mult : 1
  }
  param {
    name: "conv3_b"
	lr_mult : 2
  }
  convolution_param {
    num_output: 96
    pad: 1
    kernel_size: 3
    stride: 1
	weight_filler {
		type : "msra"
	}
	bias_filler {
		type : "constant"
	}
  }
}
layer {
  bottom: "conv3_p"
  top: "conv3_p"
  name: "conv3_relu_p"
  type: "ReLU"
}
layer {
  bottom: "conv3_p"
  top: "conv4_p"
  name: "conv4_p"
  type: "Convolution"
  param {
	name: "conv4_w"
	lr_mult : 1
  }
  param {
    name: "conv4_b"
	lr_mult : 2
  }
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
    stride: 1
	weight_filler {
		type : "msra"
	}
	bias_filler {
		type : "constant"
	}
  }
}
layer {
  bottom: "conv4_p"
  top: "conv4_p"
  name: "conv4_relu_p"
  type: "ReLU"
}
layer {
  bottom: "conv4_p"
  top: "pool4_p"
  name: "pool4_p"
  type: "Pooling"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
    pad: 0
  }
}

layer {
  bottom: "pool4_p"
  top: "pool4_p"
  type: "Dropout"
  dropout_param {
    dropout_ratio: 0.5
  }
}
# ******************end of tower P*********************